# Generated by Django 3.0.6 on 2020-05-21 11:37

from django.db import migrations, models
import weather.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=models.SET(weather.models.get_sentinel_city), to='weather.City')),
            ],
        ),
    ]
